swagger: '2.0'
info:
  version: 1.0.0
  title: LinkCXO API
  description: Articles API Specification
schemes:
  - http
host: localhost
basePath: /linkcxo-api/api
paths:
  /articles.json:
    post:
      summary: Create new article.
      description: 'Create a new article which can be like,shared and commented'
      consumes:
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: image
          type: file
          required: false
        - in: formData
          name: headline
          type: string
          required: true
        - in: formData
          name: article_text
          type: string
          required: false
        - in: formData
          name: links
          type: string
          required: false
      responses:
        '200':
          description: OK
    get:
      summary: Get all article.
      description: Get all article present on the article tab.
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: OK
  '/articles/{article_id}/.json':
    get:
      summary: Find article by ID
      description: Returns a single article
      produces:
        - application/json
      parameters:
        - name: article_id
          in: path
          description: ID of article to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
    put:
      summary: Update Article
      description: Edit and save article
      consumes:
        - application/x-www-form-urlencoded
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: path
          name: article_id
          type: string
          required: true
        - in: formData
          name: image_serialize
          type: file
          required: false
        - in: formData
          name: headline
          type: string
          required: true
        - in: formData
          name: article_text
          type: string
          required: true
        - in: formData
          name: links
          type: string
          required: false
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
    delete:
      summary: Deletes a article
      description: Delete article from DB
      produces:
        - application/xml
        - application/json
      parameters:
        - name: article_id
          in: path
          description: Article id to delete
          required: true
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
