swagger: '2.0'
info:
  version: 1.0.0
  title: LinkCXO API
  description: Common API Specification
schemes:
  - http
host: localhost
basePath: /linkcxo-api/api
tags:
  - name: Common API Endpoints 
    description: API endpoints to fetch common information 
paths:
  /countries.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of countries
      description: Fetches list of countries from database
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
  /states/{country_id}/.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of states
      description: Fetches list of states from database based on country_id
      parameters:
        - in: path
          name: country_id
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
  /cities/{state_id}/.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of cities
      description: Fetches list of cities from database based on country_id and state_id
      parameters:
        - in: path
          name: state_id
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
  /industries.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of industries
      description: Fetches list of industries from database
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
  /functional-areas.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of functional areas
      description: Fetches list of functional areas from database
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
  /designations.json:
    get:
      tags:
        - Common API Endpoints 
      summary: Get list of designations
      description: Fetches list of designations from database
      produces:
        - application/json
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: token
    in: query